services:
  frontend:
    container_name: admin-dash
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/admin-dash-template
      - /admin-dash-template/node_modules
